---
title: "Project Proposal"
author: "Roger Bukuru"
date: "`r Sys.Date()`"
output: pdf_document
---

# Section 1 - Introduction

The introduction section includes

- an introduction to the subject matter you’re investigating
- the motivation for your research question (citing any relevant literature)
- the general research question you wish to explore
- your hypotheses regarding the research question of interest.

# Section 2 - Data description

In this section, you will describe the data set you wish to explore. This includes

- description of the observations in the data set,
- description of how the data was originally collected (not how you found the data but how the original curator of the data collected it).

# Section 3 - Analysis approach

In this section, you will provide a brief overview of your analysis approach. This includes:

- Description of the response variable.
- Visualization and summary statistics for the response variable.
- List of variables that will be considered as predictors
- Regression model technique (multiple linear regression and logistic regression)