---
title: "written-report"
author: "Roger Bukuru"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Import Data 

```{r, echo = FALSE}

rm(list = ls())
library(readxl)
library(tidyverse)
library(knitr)
library(ggplot2)
library(dplyr)

file_path = "./data/default of credit card clients.xls"

credit_default_data = as_tibble(read_xls(file_path))

colnames(credit_default_data) = as.character(credit_default_data[1, ])
                                
credit_default_data = credit_default_data[-1,]


# Split Data

set.seed(10032024)
dataSize = nrow(credit_default_data)
trainingSize = floor(0.75*dataSize)

trainingDataIndices = sample(seq_len(dataSize), size = trainingSize)

training_data = credit_default_data[trainingDataIndices,]
testing_data  = credit_default_data[-trainingDataIndices,]


```


# Exploratory Data Analysis

## Feature Analysis
## Data Cleaning

## Feature Selection
## Feature Extraction



```{r, echo= FALSE}

#continous_vars = credit_default_data%>%
 #                select(where(is.))

```


```{r, echo = FALSE}

```


# Model Engineering

# Model Evaluation


